#!/bin/bash

APPDIR=$(dirname $(readlink -f "$0"))
cd "${APPDIR}"
export LD_LIBRARY_PATH=$PWD/usr/lib/:${LD_LIBRARY_PATH}
export PATH=$PWD/usr/bin/:${PATH}

show_usage() {
        USAGE_FILE=usage.txt
        [ -f $USAGE_FILE ] && {
                echo "Usage:"
                cat $USAGE_FILE
        }
}

[ -z "$*" ] && show_usage

./_BINARY_ $@

ret=$?
[ $ret != 0 ] && {
	echo "Binary returned $ret"
	ldd _BINARY_
}
