#!/bin/bash
# Author : Ismael Barros² <ismael@barros2.org>
# License : BSD http://en.wikipedia.org/wiki/BSD_license

arch="$(uname -m)"
case "$arch" in
	i386|i586|i686) arch="x86" ;;
esac		

OutputDir=..
for i in "$@"; do
	case "$i" in
		-o=*)
			OutputDir=${i#*=}
			shift
			;;
	esac
done

AppImageAssistant="$(dirname $(readlink -f "$0"))/AppImageAssistant.AppImage"
[ -f "$AppImageAssistant" ] || { echo "Could not find $AppImageAssistant"; exit 1; }

DesktopFile=$(ls -1 *.desktop | head -n1)
[ -n "$DesktopFile" ] || { echo "No package found"; exit 1; }

PackageName="$(egrep Name "$DesktopFile" | head -n1 | cut -d= -f2)-${arch}.run"

rm -if "$OutputDir/$PackageName"
echo "Building package in $OutputDir/${PackageName}..."

export LD_LIBRARY_PATH="$AppImageAssistantDir/usr/lib"
echo "$AppImageAssistant" --package . "$OutputDir/$PackageName"
"$AppImageAssistant" --package . "$OutputDir/$PackageName"
