#!/bin/bash

EXCEPTIONS=libGL.so.1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:usr/lib/

function findFiles() {
	find -iname *.so
	find -iname *.so.*
	
	[ -d "usr/bin/" ] && find "usr/bin/" -type f -perm /a+x

	for i in $@; do
		find "$i" -type f -perm /a+x
	done
}

function extractDependencies() {
	ldd $@ | grep "not found" | sort | uniq >&2
	ldd "$@" 2>/dev/null | grep -v "not a dynamic executable" | grep -v "^\." | grep -v "$PWD" | cut -d" " -f3 | grep "^/" | sort | uniq
}

mkdir -p usr/lib

prev_libs=
while true; do
	libs=$(extractDependencies $(findFiles $@))

	for i in $EXCEPTIONS; do
		#echo "Ignoring $i"
                #libs=${libs//$i/}
		for j in $libs; do
			[[ "$j" =~ "$i" ]] && {
				echo "Ignoring $j"
				libs=${libs//$j/}
			}
		done
        done

	for i in $libs; do
		lib=usr/lib/$(basename "$i")
		if [ ! -f "$lib" ]; then
			cp -v "$i" "$lib"
			chmod +x "$lib"
		fi
	done

	# If no new libraries have been found, break the loop
	if [ "$prev_libs" = "$libs" ]; then
		break;
	fi

	prev_libs=$libs
done

cp -v /lib/ld-linux.so.2 usr/lib/
