#!/bin/bash

pg4l_dir=$(dirname $(readlink -f $0))

if [ -z "$*" ]; then
	echo "Usage: $0 [binary]"
fi

cp -v "$pg4l_dir"/AppRun_quick AppRun || exit 1
for i in AppRun.desktop AppRun.png; do
	{ [ -f "$i" ] || cp -v "$pg4l_dir"/"$i" "$i"; } || exit 1
done

if [ $1 ]; then
	sed -e "s|_BINARY_|$1|g" AppRun -i
fi
