#!/bin/bash
# Author : Ismael Barros² <ismael@barros2.org>
# License : BSD http://en.wikipedia.org/wiki/BSD_license

sudo dpkg --add-architecture i386

sudo apt-get update
sudo apt-get install -y fuse
sudo apt-get install -y libc6-i386
sudo apt-get install -y libglib2.0-0:i386

if [[ "$(cat /etc/issue)" =~ "Ubuntu 14.04" ]]; then
	sudo apt-get install -y libgl1-mesa-glx-lts-quantal:i386
else
	sudo apt-get install -y libgl1-mesa-glx:i386
fi

sudo apt-get install -y libpulse0:i386 libvorbisfile3:i386
sudo apt-get install -y libglu1-mesa:i386 libxcursor1:i386

libfuse="/lib32/libfuse.so.2"
if [ -f "$libfuse" ]; then
        echo "Fuse support already installed"
else
	if ! sudo apt-get install -y libfuse2:i386; then
		pushd /tmp/ || exit 1
		wget http://archive.ubuntu.com/ubuntu/pool/main/f/fuse/libfuse2_2.9.7-1ubuntu1_i386.deb || exit 1
		dpkg -x libfuse2_2.9.7-1ubuntu1_i386.deb . || exit 1
		mkdir -p /lib32/ || exit 1
		sudo install -o root lib/i386-linux-gnu/libfuse.so.2.9.7 /lib32/libfuse.so.2 || exit 1
		rm lib/libfuse.so.2.9.7 data.tar.gz libfuse2_2.9.7-1ubuntu1_i386.deb
		rmdir lib
		sudo ldconfig
		popd
	fi
fi
